name: Docker Hub Tag Deletion
author: Josh Beard
description: Deletes specified images from a Docker Hub image after a specified date.
inputs:
  dockerhub_username:
    description: Docker Hub username
    required: true
  dockerhub_password:
    description: Docker Hub password or Personal Access Token with read/write/delete scope
    required: true
  dockerhub_repository:
    description: Docker Hub repository in the format `<namespace>/<name>`
    required: true
  dockerhub_api_base_url:
    description: The base URL of the Docker Hub API.
    default: https://hub.docker.com/v2
  date_format:
    description: >
      Format the source date is in using standard the C standard.
      See https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
      for more information.
    default: '%B %d, %Y'
  json_file:
    description: A relative path to a JSON file to parse.
  markdown_file:
    description: The relative path to the Markdown file containing a table with tags and dates.
    default: README.md
  markdown_begin_string:
    description: A string that begins the Markdown table block with tags to parse.
    default: '<!-- BEGIN deletion_table -->'
  markdown_end_string:
    description: A string that ends the Markdown table block with tags.
    default: '<!-- END deletion_table -->'
  markdown_tag_column:
    description: The column number that the tags are listed in.
    default: 1
  markdown_date_column:
    description: The table column number that the date is in.
    default: 2

runs:
  using: docker
  image: Dockerfile
  env:
    DOCKERHUB_USERNAME: ${{ inputs.dockerhub_username }}
    DOCKERHUB_PASSWORD: ${{ inputs.dockerhub_password }}
    DOCKERHUB_REPOSITORY: ${{ inputs.dockerhub_repository }}
    DOCKERHUB_API_BASE_URL: ${{ inputs.dockerhub_api_base_url }}
    MARKDOWN_FILE: ${{ inputs.markdown_file }}
    MARKDOWN_BEGIN_STRING: ${{ inputs.markdown_begin_string }}
    MARKDOWN_END_STRING: ${{ inputs.markdown_end_string }}
    MARKDOWN_TAG_COLUMN: ${{ inputs.markdown_tag_column }}
    MARKDOWN_DATE_COLUMN: ${{ inputs.markdown_date_column }}
    JSON_FILE: ${{ inputs.json_file }}
    DATE_FORMAT: ${{ inputs.date_format }}

branding:
  icon: trash-2
  color: blue

